language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  repo: foad/foad.github.io
  target_branch: master
  committer_from_gh: true
  fqdn: https://foad.dev
  keep-history: true
  on:
    branch: master
